[package]
name = "turn-me-off"
version = "0.1.0"
edition = "2021"

[dependencies]
aide = { version="0.13.2", features=["axum", "redoc"]}
axum = "0.7.4"
tokio = { version = "1.0", features = ["full"]}
tower-http = { version = "0.5.0", features = ["trace"]}
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"]}
